# Generated by Django 4.1.7 on 2023-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.TextField(blank=True, max_length=80, null=True)),
                ('github', models.CharField(blank=True, max_length=40, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=40, null=True)),
                ('instagram', models.CharField(blank=True, max_length=40, null=True)),
                ('facebook', models.CharField(blank=True, max_length=40, null=True)),
                ('tag_line', models.TextField(blank=True, max_length=50, null=True)),
                ('heading', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('image', models.ImageField(blank=True, default='noImg/no_img.jpg', null=True, upload_to='me/')),
            ],
        ),
    ]
