# Generated by Django 4.1.7 on 2023-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('job_description', models.TextField(blank=True, max_length=350, null=True)),
                ('joining_date', models.CharField(blank=True, max_length=15, null=True)),
                ('resigning_date', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, default='noImg/no_img.jpg', null=True, upload_to='experience/')),
            ],
        ),
    ]
