# Generated by Django 4.1.7 on 2023-07-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('institute', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(blank=True, default='noImg/no_img.jpg', null=True, upload_to='certificate/')),
            ],
        ),
    ]
