# Generated by Django 4.1.7 on 2023-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0004_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('potentials', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, default='noImg/no_img.jpg', null=True, upload_to='logo/')),
            ],
        ),
    ]
