# Generated by Django 4.1.7 on 2023-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0007_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('potentials', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
