# Generated by Django 4.1.7 on 2023-07-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_portfolio', '0010_rename_image_portfolio_image1_portfolio_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image5',
        ),
    ]
